# Site settings
title: Charles Korn
name: Charles Korn
email: me@charleskorn.com
description: >
  The ramblings of Charles Korn.
  I'm a developer at <a href="http://www.thoughtworks.com/">ThoughtWorks</a> in Melbourne.
  I like hardware, DevOps, travel, photography, chocolate and Lego.
baseurl: ""
url: "http://charleskorn.com"
github_username: charleskorn
permalink: pretty
author:
  name: Charles Korn
  email: me@charleskorn.com
  url: "http://charleskorn.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - CNAME
  - LICENSE
  - vendor
timezone: Australia/Melbourne

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from

# Build settings
markdown: kramdown
timezone: '+1000'
