# Site settings
title: Charles Korn
email: me@charleskorn.com
description: >
  The random ramblings of Charles Korn.
  I'm a developer at ThoughtWorks in Melbourne.
  I like hardware, DevOps, travel, photography and chocolate.
baseurl: ""
url: "http://charleskorn.com"
github_username: charleskorn

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - CNAME
  - LICENSE
  - vendor
timezone: Australia/Melbourne

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
