# Site settings
title: Charles Korn
name: Charles Korn
email: me@charleskorn.com
description: >
  The ramblings of Charles Korn.
  I'm a developer at <a href="https://www.thoughtworks.com/">Thoughtworks</a> in Melbourne, and the maintainer of <a href="https://batect.dev">Batect</a>.
  I like improving the developer experience, cloud-native architecture, internal platforms, travel, photography, chocolate and Lego.
baseurl: ""
url: "https://charleskorn.com"
github_username: charleskorn
permalink: pretty
author:
  name: Charles Korn
  email: me@charleskorn.com
  url: "https://charleskorn.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - CNAME
  - LICENSE
  - vendor
timezone: Australia/Melbourne

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from

# Build settings
markdown: kramdown
